<a href="https://colab.research.google.com/github/serivan/DeepLearning/blob/master/numerical_errors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Rounding and truncation errors

Adding a very small numb er to a larger one may have no effect. This can cause large changes downstream:

In [0]:
import numpy as np
import tensorflow as tf

sess = tf.InteractiveSession()

In [10]:
a = np.array([0., 1e-8]).astype('float32')
a

array([0.e+00, 1.e-08], dtype=float32)

In [11]:
(a+1)

array([1., 1.], dtype=float32)

In [9]:
a+1

array([1., 1.], dtype=float32)

exp(x) overflows for large x

In [30]:
x=88
np.exp(x).astype('float32')

1.6516363e+38

In [31]:
x=-100
np.exp(x).astype('float32')

3.8e-44

log(0) = - inf

In [34]:
np.log(1)

0.0

In [11]:
a = np.array([1., 88]).astype('float32')
np.log(np.sum(np.exp(a)))

88.0